Invalid HTTP_HOST header: 'checkip.amazonaws.com:443'. You may need to add 'checkip.amazonaws.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'checkip.amazonaws.com:443'. You may need to add 'checkip.amazonaws.com' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'checkip.amazonaws.com'. You may need to add 'checkip.amazonaws.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'checkip.amazonaws.com'. You may need to add 'checkip.amazonaws.com' to ALLOWED_HOSTS.
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 422, in login
    **self.each_context(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 337, in each_context
    "available_apps": self.get_app_list(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 536, in get_app_list
    app_dict = self._build_app_dict(request, app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 478, in _build_app_dict
    has_module_perms = model_admin.has_module_permission(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 611, in has_module_permission
    return request.user.has_module_perms(self.opts.app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 488, in has_module_perms
    return _user_has_module_perms(self, module)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 231, in _user_has_module_perms
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/genma/aunshop/core/backends.py", line 1, in <module>
    class PhoneBackend(ModelBackend):
NameError: name 'ModelBackend' is not defined
"GET /admin/login/?next=/admin/promotions/promotion/ HTTP/1.0" 500 150969
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 422, in login
    **self.each_context(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 337, in each_context
    "available_apps": self.get_app_list(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 536, in get_app_list
    app_dict = self._build_app_dict(request, app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 478, in _build_app_dict
    has_module_perms = model_admin.has_module_permission(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 611, in has_module_permission
    return request.user.has_module_perms(self.opts.app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 488, in has_module_perms
    return _user_has_module_perms(self, module)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 231, in _user_has_module_perms
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/genma/aunshop/core/backends.py", line 1, in <module>
    class PhoneBackend(ModelBackend):
NameError: name 'ModelBackend' is not defined
"GET /admin/login/?next=/admin/promotions/promotionimage/ HTTP/1.0" 500 150897
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 422, in login
    **self.each_context(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 337, in each_context
    "available_apps": self.get_app_list(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 536, in get_app_list
    app_dict = self._build_app_dict(request, app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 478, in _build_app_dict
    has_module_perms = model_admin.has_module_permission(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 611, in has_module_permission
    return request.user.has_module_perms(self.opts.app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 488, in has_module_perms
    return _user_has_module_perms(self, module)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 231, in _user_has_module_perms
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/genma/aunshop/core/backends.py", line 1, in <module>
    class PhoneBackend(ModelBackend):
NameError: name 'ModelBackend' is not defined
"GET /admin/login/?next=/admin/promotions/promotionimage/add/ HTTP/1.0" 500 150945
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/jazzmin/templatetags/jazzmin.py", line 112, in get_top_menu
    return make_menu(user, options.get("topmenu_links", []), options, allow_appmenus=True, admin_site=admin_site)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/jazzmin/utils.py", line 164, in make_menu
    model_permissions = get_view_permissions(user)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/jazzmin/utils.py", line 146, in get_view_permissions
    perms = user.get_all_permissions()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 296, in get_all_permissions
    return _user_get_permissions(self, obj, "all")
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 206, in _user_get_permissions
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/genma/aunshop/core/backends.py", line 1, in <module>
    class PhoneBackend(ModelBackend):
NameError: name 'ModelBackend' is not defined
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/jazzmin/templatetags/jazzmin.py", line 112, in get_top_menu
    return make_menu(user, options.get("topmenu_links", []), options, allow_appmenus=True, admin_site=admin_site)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/jazzmin/utils.py", line 164, in make_menu
    model_permissions = get_view_permissions(user)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/jazzmin/utils.py", line 146, in get_view_permissions
    perms = user.get_all_permissions()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 296, in get_all_permissions
    return _user_get_permissions(self, obj, "all")
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 206, in _user_get_permissions
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/genma/aunshop/core/backends.py", line 1, in <module>
    class PhoneBackend(ModelBackend):
NameError: name 'ModelBackend' is not defined
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/jazzmin/templatetags/jazzmin.py", line 112, in get_top_menu
    return make_menu(user, options.get("topmenu_links", []), options, allow_appmenus=True, admin_site=admin_site)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/jazzmin/utils.py", line 164, in make_menu
    model_permissions = get_view_permissions(user)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/jazzmin/utils.py", line 146, in get_view_permissions
    perms = user.get_all_permissions()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 296, in get_all_permissions
    return _user_get_permissions(self, obj, "all")
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 206, in _user_get_permissions
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/genma/aunshop/core/backends.py", line 1, in <module>
    class PhoneBackend(ModelBackend):
NameError: name 'ModelBackend' is not defined
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/jazzmin/templatetags/jazzmin.py", line 112, in get_top_menu
    return make_menu(user, options.get("topmenu_links", []), options, allow_appmenus=True, admin_site=admin_site)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/jazzmin/utils.py", line 164, in make_menu
    model_permissions = get_view_permissions(user)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/jazzmin/utils.py", line 146, in get_view_permissions
    perms = user.get_all_permissions()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 296, in get_all_permissions
    return _user_get_permissions(self, obj, "all")
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 206, in _user_get_permissions
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/genma/aunshop/core/backends.py", line 1, in <module>
    class PhoneBackend(ModelBackend):
NameError: name 'ModelBackend' is not defined
Invalid HTTP_HOST header: '90.151.171.106:443'. You may need to add '90.151.171.106' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '90.151.171.106:443'. You may need to add '90.151.171.106' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '90.151.171.106'. You may need to add '90.151.171.106' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '90.151.171.106'. You may need to add '90.151.171.106' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '/run/gunicorn-dev.sock:'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '/run/gunicorn-dev.sock:'. The domain name provided is not valid according to RFC 1034/1035.
Internal Server Error: /admin/users/customuser/1/change/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/jazzmin/templatetags/jazzmin.py", line 112, in get_top_menu
    return make_menu(user, options.get("topmenu_links", []), options, allow_appmenus=True, admin_site=admin_site)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/jazzmin/utils.py", line 164, in make_menu
    model_permissions = get_view_permissions(user)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/jazzmin/utils.py", line 146, in get_view_permissions
    perms = user.get_all_permissions()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 296, in get_all_permissions
    return _user_get_permissions(self, obj, "all")
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 206, in _user_get_permissions
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users.authentication'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/jazzmin/templatetags/jazzmin.py", line 112, in get_top_menu
    return make_menu(user, options.get("topmenu_links", []), options, allow_appmenus=True, admin_site=admin_site)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/jazzmin/utils.py", line 164, in make_menu
    model_permissions = get_view_permissions(user)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/jazzmin/utils.py", line 146, in get_view_permissions
    perms = user.get_all_permissions()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 296, in get_all_permissions
    return _user_get_permissions(self, obj, "all")
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 206, in _user_get_permissions
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users.authentication'
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 422, in login
    **self.each_context(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 337, in each_context
    "available_apps": self.get_app_list(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 536, in get_app_list
    app_dict = self._build_app_dict(request, app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 478, in _build_app_dict
    has_module_perms = model_admin.has_module_permission(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 611, in has_module_permission
    return request.user.has_module_perms(self.opts.app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 488, in has_module_perms
    return _user_has_module_perms(self, module)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 231, in _user_has_module_perms
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users.authentication'
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 422, in login
    **self.each_context(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 337, in each_context
    "available_apps": self.get_app_list(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 536, in get_app_list
    app_dict = self._build_app_dict(request, app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 478, in _build_app_dict
    has_module_perms = model_admin.has_module_permission(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 611, in has_module_permission
    return request.user.has_module_perms(self.opts.app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 488, in has_module_perms
    return _user_has_module_perms(self, module)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 231, in _user_has_module_perms
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users.authentication'
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 422, in login
    **self.each_context(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 337, in each_context
    "available_apps": self.get_app_list(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 536, in get_app_list
    app_dict = self._build_app_dict(request, app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 478, in _build_app_dict
    has_module_perms = model_admin.has_module_permission(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 611, in has_module_permission
    return request.user.has_module_perms(self.opts.app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 488, in has_module_perms
    return _user_has_module_perms(self, module)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 231, in _user_has_module_perms
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users.authentication'
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 422, in login
    **self.each_context(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 337, in each_context
    "available_apps": self.get_app_list(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 536, in get_app_list
    app_dict = self._build_app_dict(request, app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 478, in _build_app_dict
    has_module_perms = model_admin.has_module_permission(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 611, in has_module_permission
    return request.user.has_module_perms(self.opts.app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 488, in has_module_perms
    return _user_has_module_perms(self, module)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 231, in _user_has_module_perms
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users.authentication'
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 422, in login
    **self.each_context(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 337, in each_context
    "available_apps": self.get_app_list(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 536, in get_app_list
    app_dict = self._build_app_dict(request, app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 478, in _build_app_dict
    has_module_perms = model_admin.has_module_permission(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 611, in has_module_permission
    return request.user.has_module_perms(self.opts.app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 488, in has_module_perms
    return _user_has_module_perms(self, module)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 231, in _user_has_module_perms
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users.authentication'
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 422, in login
    **self.each_context(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 337, in each_context
    "available_apps": self.get_app_list(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 536, in get_app_list
    app_dict = self._build_app_dict(request, app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 478, in _build_app_dict
    has_module_perms = model_admin.has_module_permission(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 611, in has_module_permission
    return request.user.has_module_perms(self.opts.app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 488, in has_module_perms
    return _user_has_module_perms(self, module)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 231, in _user_has_module_perms
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users.authentication'
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 422, in login
    **self.each_context(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 337, in each_context
    "available_apps": self.get_app_list(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 536, in get_app_list
    app_dict = self._build_app_dict(request, app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 478, in _build_app_dict
    has_module_perms = model_admin.has_module_permission(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 611, in has_module_permission
    return request.user.has_module_perms(self.opts.app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 488, in has_module_perms
    return _user_has_module_perms(self, module)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 231, in _user_has_module_perms
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users.authentication'
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 422, in login
    **self.each_context(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 337, in each_context
    "available_apps": self.get_app_list(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 536, in get_app_list
    app_dict = self._build_app_dict(request, app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 478, in _build_app_dict
    has_module_perms = model_admin.has_module_permission(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 611, in has_module_permission
    return request.user.has_module_perms(self.opts.app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 488, in has_module_perms
    return _user_has_module_perms(self, module)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 231, in _user_has_module_perms
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users.authentication'
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 422, in login
    **self.each_context(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 337, in each_context
    "available_apps": self.get_app_list(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 536, in get_app_list
    app_dict = self._build_app_dict(request, app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 478, in _build_app_dict
    has_module_perms = model_admin.has_module_permission(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 611, in has_module_permission
    return request.user.has_module_perms(self.opts.app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 488, in has_module_perms
    return _user_has_module_perms(self, module)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 231, in _user_has_module_perms
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users.authentication'
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 422, in login
    **self.each_context(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 337, in each_context
    "available_apps": self.get_app_list(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 536, in get_app_list
    app_dict = self._build_app_dict(request, app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 478, in _build_app_dict
    has_module_perms = model_admin.has_module_permission(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 611, in has_module_permission
    return request.user.has_module_perms(self.opts.app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 488, in has_module_perms
    return _user_has_module_perms(self, module)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 231, in _user_has_module_perms
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users.authentication'
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 422, in login
    **self.each_context(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 337, in each_context
    "available_apps": self.get_app_list(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 536, in get_app_list
    app_dict = self._build_app_dict(request, app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 478, in _build_app_dict
    has_module_perms = model_admin.has_module_permission(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 611, in has_module_permission
    return request.user.has_module_perms(self.opts.app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 488, in has_module_perms
    return _user_has_module_perms(self, module)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 231, in _user_has_module_perms
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users.authentication'
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 422, in login
    **self.each_context(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 337, in each_context
    "available_apps": self.get_app_list(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 536, in get_app_list
    app_dict = self._build_app_dict(request, app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 478, in _build_app_dict
    has_module_perms = model_admin.has_module_permission(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 611, in has_module_permission
    return request.user.has_module_perms(self.opts.app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 488, in has_module_perms
    return _user_has_module_perms(self, module)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 231, in _user_has_module_perms
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users.authentication'
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 422, in login
    **self.each_context(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 337, in each_context
    "available_apps": self.get_app_list(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 536, in get_app_list
    app_dict = self._build_app_dict(request, app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 478, in _build_app_dict
    has_module_perms = model_admin.has_module_permission(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 611, in has_module_permission
    return request.user.has_module_perms(self.opts.app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 488, in has_module_perms
    return _user_has_module_perms(self, module)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 231, in _user_has_module_perms
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users.authentication'
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 422, in login
    **self.each_context(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 337, in each_context
    "available_apps": self.get_app_list(request),
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 536, in get_app_list
    app_dict = self._build_app_dict(request, app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 478, in _build_app_dict
    has_module_perms = model_admin.has_module_permission(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 611, in has_module_permission
    return request.user.has_module_perms(self.opts.app_label)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 488, in has_module_perms
    return _user_has_module_perms(self, module)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 231, in _user_has_module_perms
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users.authentication'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/template/library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/jazzmin/templatetags/jazzmin.py", line 112, in get_top_menu
    return make_menu(user, options.get("topmenu_links", []), options, allow_appmenus=True, admin_site=admin_site)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/jazzmin/utils.py", line 164, in make_menu
    model_permissions = get_view_permissions(user)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/jazzmin/utils.py", line 146, in get_view_permissions
    perms = user.get_all_permissions()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 296, in get_all_permissions
    return _user_get_permissions(self, obj, "all")
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 206, in _user_get_permissions
    for backend in auth.get_backends():
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
    return _get_backends(return_tuples=False)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users.authentication'
Internal Server Error: /api/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/genma/aunshop/users/views.py", line 27, in post
    user = authenticate(request, username=phone, password=password)
NameError: name 'authenticate' is not defined
Internal Server Error: /api/token/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework_simplejwt/views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 447, in run_validation
    value = self.validate(value)
  File "/home/genma/aunshop/users/jwt_serializers.py", line 26, in validate
    return super().validate(attrs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework_simplejwt/serializers.py", line 73, in validate
    data = super().validate(attrs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework_simplejwt/serializers.py", line 54, in validate
    self.user = authenticate(**authenticate_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 68, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users.authentication'
Internal Server Error: /api/token/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework_simplejwt/views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 447, in run_validation
    value = self.validate(value)
  File "/home/genma/aunshop/users/jwt_serializers.py", line 26, in validate
    return super().validate(attrs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework_simplejwt/serializers.py", line 73, in validate
    data = super().validate(attrs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework_simplejwt/serializers.py", line 54, in validate
    self.user = authenticate(**authenticate_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 68, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users.authentication'
Internal Server Error: /api/token/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework_simplejwt/views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 447, in run_validation
    value = self.validate(value)
  File "/home/genma/aunshop/users/jwt_serializers.py", line 26, in validate
    return super().validate(attrs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework_simplejwt/serializers.py", line 73, in validate
    data = super().validate(attrs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework_simplejwt/serializers.py", line 54, in validate
    self.user = authenticate(**authenticate_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 68, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users.authentication'
Internal Server Error: /api/token/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework_simplejwt/views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 447, in run_validation
    value = self.validate(value)
  File "/home/genma/aunshop/users/jwt_serializers.py", line 26, in validate
    return super().validate(attrs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework_simplejwt/serializers.py", line 73, in validate
    data = super().validate(attrs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework_simplejwt/serializers.py", line 54, in validate
    self.user = authenticate(**authenticate_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 68, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users.authentication'
Internal Server Error: /api/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/genma/aunshop/users/views.py", line 27, in post
    user = authenticate(request, username=phone, password=password)
NameError: name 'authenticate' is not defined
Internal Server Error: /api/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/genma/aunshop/users/views.py", line 27, in post
    user = authenticate(request, username=phone, password=password)
NameError: name 'authenticate' is not defined
Internal Server Error: /api/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/genma/aunshop/users/views.py", line 27, in post
    user = authenticate(request, username=phone, password=password)
NameError: name 'authenticate' is not defined
Internal Server Error: /api/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/genma/aunshop/users/views.py", line 27, in post
    user = authenticate(request, username=phone, password=password)
NameError: name 'authenticate' is not defined
Internal Server Error: /api/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/genma/aunshop/users/views.py", line 27, in post
    user = authenticate(request, username=phone, password=password)
NameError: name 'authenticate' is not defined
Internal Server Error: /api/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/genma/aunshop/users/views.py", line 27, in post
    user = authenticate(request, username=phone, password=password)
NameError: name 'authenticate' is not defined
Internal Server Error: /api/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/genma/aunshop/users/views.py", line 27, in post
    user = authenticate(request, username=phone, password=password)
NameError: name 'authenticate' is not defined
Internal Server Error: /api/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/genma/aunshop/users/views.py", line 27, in post
    user = authenticate(request, username=phone, password=password)
NameError: name 'authenticate' is not defined
Internal Server Error: /api/login/
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/genma/aunshop/users/views.py", line 27, in post
NameError: name 'authenticate' is not defined
Invalid HTTP_HOST header: '141.76.94.18'. You may need to add '141.76.94.18' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/genma/aunshop/venv/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '141.76.94.18'. You may need to add '141.76.94.18' to ALLOWED_HOSTS.
